""" Contains all the data models used in inputs/outputs """

from .access_control_ui_access_mode import AccessControlUIAccessMode
from .access_group_info import AccessGroupInfo
from .active_users_analytics_response import ActiveUsersAnalyticsResponse
from .add_team_callback import AddTeamCallback
from .add_team_callback_callback_type_type_0 import AddTeamCallbackCallbackTypeType0
from .add_team_callback_callback_vars import AddTeamCallbackCallbackVars
from .agent_capabilities import AgentCapabilities
from .agent_card import AgentCard
from .agent_card_security_schemes_type_0 import AgentCardSecuritySchemesType0
from .agent_card_security_type_0_item import AgentCardSecurityType0Item
from .agent_card_signature import AgentCardSignature
from .agent_card_signature_header_type_0 import AgentCardSignatureHeaderType0
from .agent_config import AgentConfig
from .agent_config_litellm_params import AgentConfigLitellmParams
from .agent_create_info import AgentCreateInfo
from .agent_create_info_litellm_params_template_type_0 import AgentCreateInfoLitellmParamsTemplateType0
from .agent_credential_field import AgentCredentialField
from .agent_credential_field_field_type import AgentCredentialFieldFieldType
from .agent_extension import AgentExtension
from .agent_extension_params_type_0 import AgentExtensionParamsType0
from .agent_interface import AgentInterface
from .agent_make_public_response import AgentMakePublicResponse
from .agent_provider import AgentProvider
from .agent_response import AgentResponse
from .agent_response_agent_card_params import AgentResponseAgentCardParams
from .agent_response_litellm_params_type_0 import AgentResponseLitellmParamsType0
from .agent_skill import AgentSkill
from .agent_skill_security_type_0_item import AgentSkillSecurityType0Item
from .allowed_vector_store_index_item import AllowedVectorStoreIndexItem
from .allowed_vector_store_index_item_index_permissions_item import AllowedVectorStoreIndexItemIndexPermissionsItem
from .api_key_security_scheme import APIKeySecurityScheme
from .api_key_security_scheme_in import APIKeySecuritySchemeIn
from .apply_guardrail_request import ApplyGuardrailRequest
from .apply_guardrail_response import ApplyGuardrailResponse
from .audit_log_response import AuditLogResponse
from .audit_log_response_before_value_type_0 import AuditLogResponseBeforeValueType0
from .audit_log_response_updated_values_type_0 import AuditLogResponseUpdatedValuesType0
from .base_litellm_params import BaseLitellmParams
from .base_litellm_params_additional_provider_specific_params_type_0 import BaseLitellmParamsAdditionalProviderSpecificParamsType0
from .base_litellm_params_detect_secrets_config_type_0 import BaseLitellmParamsDetectSecretsConfigType0
from .block_key_request import BlockKeyRequest
from .block_team_request import BlockTeamRequest
from .block_users import BlockUsers
from .blocked_word import BlockedWord
from .body_audio_transcriptions_audio_transcriptions_post import BodyAudioTranscriptionsAudioTranscriptionsPost
from .body_audio_transcriptions_v1_audio_transcriptions_post import BodyAudioTranscriptionsV1AudioTranscriptionsPost
from .body_convert_prompt_file_to_json_utils_dotprompt_json_converter_post import BodyConvertPromptFileToJsonUtilsDotpromptJsonConverterPost
from .body_create_file_files_post import BodyCreateFileFilesPost
from .body_create_file_provider_v1_files_post import BodyCreateFileProviderV1FilesPost
from .body_create_file_v1_files_post import BodyCreateFileV1FilesPost
from .body_test_model_connection_health_test_connection_post import BodyTestModelConnectionHealthTestConnectionPost
from .body_test_model_connection_health_test_connection_post_litellm_params import BodyTestModelConnectionHealthTestConnectionPostLitellmParams
from .body_test_model_connection_health_test_connection_post_mode_type_0 import BodyTestModelConnectionHealthTestConnectionPostModeType0
from .body_test_model_connection_health_test_connection_post_model_info import BodyTestModelConnectionHealthTestConnectionPostModelInfo
from .body_token_endpoint_mcp_server_name_token_post import BodyTokenEndpointMcpServerNameTokenPost
from .body_token_endpoint_token_post import BodyTokenEndpointTokenPost
from .body_upload_logo_upload_logo_post import BodyUploadLogoUploadLogoPost
from .body_video_generation_v1_videos_post import BodyVideoGenerationV1VideosPost
from .body_video_generation_videos_post import BodyVideoGenerationVideosPost
from .breakdown_metrics import BreakdownMetrics
from .breakdown_metrics_api_keys import BreakdownMetricsApiKeys
from .breakdown_metrics_endpoints import BreakdownMetricsEndpoints
from .breakdown_metrics_entities import BreakdownMetricsEntities
from .breakdown_metrics_mcp_servers import BreakdownMetricsMcpServers
from .breakdown_metrics_model_groups import BreakdownMetricsModelGroups
from .breakdown_metrics_models import BreakdownMetricsModels
from .breakdown_metrics_providers import BreakdownMetricsProviders
from .budget_config import BudgetConfig
from .budget_delete_request import BudgetDeleteRequest
from .budget_new_request import BudgetNewRequest
from .budget_new_request_model_max_budget_type_0 import BudgetNewRequestModelMaxBudgetType0
from .budget_request import BudgetRequest
from .bulk_team_member_add_request import BulkTeamMemberAddRequest
from .bulk_team_member_add_response import BulkTeamMemberAddResponse
from .bulk_team_member_add_response_updated_team_type_0 import BulkTeamMemberAddResponseUpdatedTeamType0
from .bulk_update_user_request import BulkUpdateUserRequest
from .bulk_update_user_response import BulkUpdateUserResponse
from .cache_ping_response import CachePingResponse
from .cache_ping_response_health_check_cache_params_type_0 import CachePingResponseHealthCheckCacheParamsType0
from .cache_settings_field import CacheSettingsField
from .cache_settings_response import CacheSettingsResponse
from .cache_settings_response_current_values import CacheSettingsResponseCurrentValues
from .cache_settings_response_redis_type_descriptions import CacheSettingsResponseRedisTypeDescriptions
from .cache_settings_update_request import CacheSettingsUpdateRequest
from .cache_settings_update_request_cache_settings import CacheSettingsUpdateRequestCacheSettings
from .cache_test_request import CacheTestRequest
from .cache_test_request_cache_settings import CacheTestRequestCacheSettings
from .cache_test_response import CacheTestResponse
from .call_types import CallTypes
from .callbacks_by_type import CallbacksByType
from .chat_completion_annotation import ChatCompletionAnnotation
from .chat_completion_annotation_url_citation import ChatCompletionAnnotationURLCitation
from .chat_completion_assistant_message import ChatCompletionAssistantMessage
from .chat_completion_assistant_tool_call import ChatCompletionAssistantToolCall
from .chat_completion_audio_object import ChatCompletionAudioObject
from .chat_completion_audio_response import ChatCompletionAudioResponse
from .chat_completion_cached_content import ChatCompletionCachedContent
from .chat_completion_chat_completions_post_body import ChatCompletionChatCompletionsPostBody
from .chat_completion_chat_completions_post_body_context_window_fallback_dict_type_0 import ChatCompletionChatCompletionsPostBodyContextWindowFallbackDictType0
from .chat_completion_chat_completions_post_body_function_call_type_1 import ChatCompletionChatCompletionsPostBodyFunctionCallType1
from .chat_completion_chat_completions_post_body_functions_type_0_item import ChatCompletionChatCompletionsPostBodyFunctionsType0Item
from .chat_completion_chat_completions_post_body_logit_bias_type_0 import ChatCompletionChatCompletionsPostBodyLogitBiasType0
from .chat_completion_chat_completions_post_body_metadata_type_0 import ChatCompletionChatCompletionsPostBodyMetadataType0
from .chat_completion_chat_completions_post_body_response_format_type_0 import ChatCompletionChatCompletionsPostBodyResponseFormatType0
from .chat_completion_chat_completions_post_body_stream_options_type_0 import ChatCompletionChatCompletionsPostBodyStreamOptionsType0
from .chat_completion_chat_completions_post_body_tool_choice_type_1 import ChatCompletionChatCompletionsPostBodyToolChoiceType1
from .chat_completion_chat_completions_post_body_tools_type_0_item import ChatCompletionChatCompletionsPostBodyToolsType0Item
from .chat_completion_developer_message import ChatCompletionDeveloperMessage
from .chat_completion_document_object import ChatCompletionDocumentObject
from .chat_completion_file_object import ChatCompletionFileObject
from .chat_completion_file_object_file import ChatCompletionFileObjectFile
from .chat_completion_function_message import ChatCompletionFunctionMessage
from .chat_completion_image_object import ChatCompletionImageObject
from .chat_completion_image_url_object import ChatCompletionImageUrlObject
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
from .chat_completion_redacted_thinking_block import ChatCompletionRedactedThinkingBlock
from .chat_completion_redacted_thinking_block_cache_control_type_0 import ChatCompletionRedactedThinkingBlockCacheControlType0
from .chat_completion_system_message import ChatCompletionSystemMessage
from .chat_completion_text_object import ChatCompletionTextObject
from .chat_completion_thinking_block import ChatCompletionThinkingBlock
from .chat_completion_thinking_block_cache_control_type_0 import ChatCompletionThinkingBlockCacheControlType0
from .chat_completion_token_logprob import ChatCompletionTokenLogprob
from .chat_completion_tool_call_function_chunk import ChatCompletionToolCallFunctionChunk
from .chat_completion_tool_call_function_chunk_provider_specific_fields_type_0 import ChatCompletionToolCallFunctionChunkProviderSpecificFieldsType0
from .chat_completion_tool_message import ChatCompletionToolMessage
from .chat_completion_user_message import ChatCompletionUserMessage
from .chat_completion_v1_chat_completions_post_body import ChatCompletionV1ChatCompletionsPostBody
from .chat_completion_v1_chat_completions_post_body_context_window_fallback_dict_type_0 import ChatCompletionV1ChatCompletionsPostBodyContextWindowFallbackDictType0
from .chat_completion_v1_chat_completions_post_body_function_call_type_1 import ChatCompletionV1ChatCompletionsPostBodyFunctionCallType1
from .chat_completion_v1_chat_completions_post_body_functions_type_0_item import ChatCompletionV1ChatCompletionsPostBodyFunctionsType0Item
from .chat_completion_v1_chat_completions_post_body_logit_bias_type_0 import ChatCompletionV1ChatCompletionsPostBodyLogitBiasType0
from .chat_completion_v1_chat_completions_post_body_metadata_type_0 import ChatCompletionV1ChatCompletionsPostBodyMetadataType0
from .chat_completion_v1_chat_completions_post_body_response_format_type_0 import ChatCompletionV1ChatCompletionsPostBodyResponseFormatType0
from .chat_completion_v1_chat_completions_post_body_stream_options_type_0 import ChatCompletionV1ChatCompletionsPostBodyStreamOptionsType0
from .chat_completion_v1_chat_completions_post_body_tool_choice_type_1 import ChatCompletionV1ChatCompletionsPostBodyToolChoiceType1
from .chat_completion_v1_chat_completions_post_body_tools_type_0_item import ChatCompletionV1ChatCompletionsPostBodyToolsType0Item
from .chat_completion_video_object import ChatCompletionVideoObject
from .chat_completion_video_url_object import ChatCompletionVideoUrlObject
from .choice_logprobs import ChoiceLogprobs
from .choices import Choices
from .choices_provider_specific_fields_type_0 import ChoicesProviderSpecificFieldsType0
from .citations_object import CitationsObject
from .cloud_zero_export_request import CloudZeroExportRequest
from .cloud_zero_export_response import CloudZeroExportResponse
from .cloud_zero_export_response_dry_run_data_type_0 import CloudZeroExportResponseDryRunDataType0
from .cloud_zero_export_response_summary_type_0 import CloudZeroExportResponseSummaryType0
from .cloud_zero_init_request import CloudZeroInitRequest
from .cloud_zero_init_response import CloudZeroInitResponse
from .cloud_zero_settings_update import CloudZeroSettingsUpdate
from .cloud_zero_settings_view import CloudZeroSettingsView
from .configurable_clientside_params_custom_auth import ConfigurableClientsideParamsCustomAuth
from .content_filter_action import ContentFilterAction
from .content_filter_pattern import ContentFilterPattern
from .content_filter_pattern_pattern_type import ContentFilterPatternPatternType
from .convert_prompt_file_to_json_utils_dotprompt_json_converter_post_response_convert_prompt_file_to_json_utils_dotprompt_json_converter_post import ConvertPromptFileToJsonUtilsDotpromptJsonConverterPostResponseConvertPromptFileToJsonUtilsDotpromptJsonConverterPost
from .cost_estimate_request import CostEstimateRequest
from .cost_estimate_response import CostEstimateResponse
from .create_credential_item import CreateCredentialItem
from .create_credential_item_credential_info import CreateCredentialItemCredentialInfo
from .create_credential_item_credential_values_type_0 import CreateCredentialItemCredentialValuesType0
from .create_guardrail_request import CreateGuardrailRequest
from .create_search_tool_request import CreateSearchToolRequest
from .credential_item import CredentialItem
from .credential_item_credential_info import CredentialItemCredentialInfo
from .credential_item_credential_values import CredentialItemCredentialValues
from .daily_spend_data import DailySpendData
from .daily_spend_metadata import DailySpendMetadata
from .default_internal_user_params import DefaultInternalUserParams
from .default_internal_user_params_user_role_type_0 import DefaultInternalUserParamsUserRoleType0
from .default_team_settings_response import DefaultTeamSettingsResponse
from .default_team_settings_response_field_schema import DefaultTeamSettingsResponseFieldSchema
from .default_team_settings_response_values import DefaultTeamSettingsResponseValues
from .default_team_sso_params import DefaultTeamSSOParams
from .delete_customer_request import DeleteCustomerRequest
from .delete_fallback_fallback_model_delete_fallback_type import DeleteFallbackFallbackModelDeleteFallbackType
from .delete_model_group_response import DeleteModelGroupResponse
from .delete_organization_request import DeleteOrganizationRequest
from .delete_skill_response import DeleteSkillResponse
from .delete_team_request import DeleteTeamRequest
from .delete_user_request import DeleteUserRequest
from .deployment import Deployment
from .distinct_tag_response import DistinctTagResponse
from .distinct_tags_response import DistinctTagsResponse
from .document_object import DocumentObject
from .email_event import EmailEvent
from .email_event_settings import EmailEventSettings
from .email_event_settings_response import EmailEventSettingsResponse
from .email_event_settings_update_request import EmailEventSettingsUpdateRequest
from .embedding_request import EmbeddingRequest
from .embedding_request_custom_llm_provider_type_1 import EmbeddingRequestCustomLlmProviderType1
from .embedding_request_litellm_logging_obj_type_0 import EmbeddingRequestLitellmLoggingObjType0
from .embeddings_embeddings_post_body import EmbeddingsEmbeddingsPostBody
from .embeddings_embeddings_post_body_custom_llm_provider_type_1 import EmbeddingsEmbeddingsPostBodyCustomLlmProviderType1
from .embeddings_embeddings_post_body_litellm_logging_obj_type_0 import EmbeddingsEmbeddingsPostBodyLitellmLoggingObjType0
from .embeddings_v1_embeddings_post_body import EmbeddingsV1EmbeddingsPostBody
from .embeddings_v1_embeddings_post_body_custom_llm_provider_type_1 import EmbeddingsV1EmbeddingsPostBodyCustomLlmProviderType1
from .embeddings_v1_embeddings_post_body_litellm_logging_obj_type_0 import EmbeddingsV1EmbeddingsPostBodyLitellmLoggingObjType0
from .error_response import ErrorResponse
from .error_response_detail import ErrorResponseDetail
from .fallback_create_request import FallbackCreateRequest
from .fallback_create_request_fallback_type import FallbackCreateRequestFallbackType
from .fallback_delete_response import FallbackDeleteResponse
from .fallback_get_response import FallbackGetResponse
from .fallback_response import FallbackResponse
from .function_call import FunctionCall
from .get_fallback_fallback_model_get_fallback_type import GetFallbackFallbackModelGetFallbackType
from .get_global_spend_report_global_spend_report_get_group_by_type_0 import GetGlobalSpendReportGlobalSpendReportGetGroupByType0
from .get_team_member_permissions_response import GetTeamMemberPermissionsResponse
from .gray_swan_guardrail_config_model_optional_params import GraySwanGuardrailConfigModelOptionalParams
from .gray_swan_guardrail_config_model_optional_params_categories_type_0 import GraySwanGuardrailConfigModelOptionalParamsCategoriesType0
from .guardrail import Guardrail
from .guardrail_guardrail_info_type_0 import GuardrailGuardrailInfoType0
from .guardrail_info_response import GuardrailInfoResponse
from .guardrail_info_response_guardrail_info_type_0 import GuardrailInfoResponseGuardrailInfoType0
from .guardraildefinitionlocation import GUARDRAILDEFINITIONLOCATION
from .health_services_endpoint_health_services_get_service_type_0 import HealthServicesEndpointHealthServicesGetServiceType0
from .http_auth_security_scheme import HTTPAuthSecurityScheme
from .http_validation_error import HTTPValidationError
from .hyperparameters import Hyperparameters
from .image_url_list_item import ImageURLListItem
from .image_url_object import ImageURLObject
from .index_create_lite_llm_params import IndexCreateLiteLLMParams
from .index_create_request import IndexCreateRequest
from .index_create_request_index_info_type_0 import IndexCreateRequestIndexInfoType0
from .input_audio import InputAudio
from .input_audio_format import InputAudioFormat
from .internal_user_settings_response import InternalUserSettingsResponse
from .internal_user_settings_response_field_schema import InternalUserSettingsResponseFieldSchema
from .internal_user_settings_response_values import InternalUserSettingsResponseValues
from .ip_address import IPAddress
from .key_aliases_key_aliases_get_response_key_aliases_key_aliases_get import KeyAliasesKeyAliasesGetResponseKeyAliasesKeyAliasesGet
from .key_health_response import KeyHealthResponse
from .key_health_response_key import KeyHealthResponseKey
from .key_list_response_object import KeyListResponseObject
from .key_metadata import KeyMetadata
from .key_metric_with_metadata import KeyMetricWithMetadata
from .key_request import KeyRequest
from .lakera_category_thresholds import LakeraCategoryThresholds
from .list_access_groups_response import ListAccessGroupsResponse
from .list_fine_tuning_jobs_fine_tuning_jobs_get_custom_llm_provider_type_0 import ListFineTuningJobsFineTuningJobsGetCustomLlmProviderType0
from .list_fine_tuning_jobs_v1_fine_tuning_jobs_get_custom_llm_provider_type_0 import ListFineTuningJobsV1FineTuningJobsGetCustomLlmProviderType0
from .list_guardrails_response import ListGuardrailsResponse
from .list_prompts_response import ListPromptsResponse
from .list_search_tools_response import ListSearchToolsResponse
from .list_skills_response import ListSkillsResponse
from .list_tool_rest_api_mcp_rest_tools_list_get_response_list_tool_rest_api_mcp_rest_tools_list_get import ListToolRestApiMcpRestToolsListGetResponseListToolRestApiMcpRestToolsListGet
from .lite_llm_budget_table import LiteLLMBudgetTable
from .lite_llm_budget_table_model_max_budget_type_0 import LiteLLMBudgetTableModelMaxBudgetType0
from .lite_llm_deleted_team_table import LiteLLMDeletedTeamTable
from .lite_llm_deleted_team_table_metadata_type_0 import LiteLLMDeletedTeamTableMetadataType0
from .lite_llm_deleted_team_table_router_settings_type_0 import LiteLLMDeletedTeamTableRouterSettingsType0
from .lite_llm_deleted_verification_token import LiteLLMDeletedVerificationToken
from .lite_llm_deleted_verification_token_aliases import LiteLLMDeletedVerificationTokenAliases
from .lite_llm_deleted_verification_token_config import LiteLLMDeletedVerificationTokenConfig
from .lite_llm_deleted_verification_token_litellm_budget_table_type_0 import LiteLLMDeletedVerificationTokenLitellmBudgetTableType0
from .lite_llm_deleted_verification_token_metadata import LiteLLMDeletedVerificationTokenMetadata
from .lite_llm_deleted_verification_token_model_max_budget import LiteLLMDeletedVerificationTokenModelMaxBudget
from .lite_llm_deleted_verification_token_model_spend import LiteLLMDeletedVerificationTokenModelSpend
from .lite_llm_deleted_verification_token_permissions import LiteLLMDeletedVerificationTokenPermissions
from .lite_llm_deleted_verification_token_router_settings_type_0 import LiteLLMDeletedVerificationTokenRouterSettingsType0
from .lite_llm_end_user_table import LiteLLMEndUserTable
from .lite_llm_end_user_table_allowed_model_region_type_0 import LiteLLMEndUserTableAllowedModelRegionType0
from .lite_llm_fine_tuning_job_create import LiteLLMFineTuningJobCreate
from .lite_llm_fine_tuning_job_create_custom_llm_provider_type_0 import LiteLLMFineTuningJobCreateCustomLlmProviderType0
from .lite_llm_key_type import LiteLLMKeyType
from .lite_llm_managed_vector_store import LiteLLMManagedVectorStore
from .lite_llm_managed_vector_store_list_response import LiteLLMManagedVectorStoreListResponse
from .lite_llm_managed_vector_store_litellm_params_type_0 import LiteLLMManagedVectorStoreLitellmParamsType0
from .lite_llm_managed_vector_store_vector_store_metadata_type_0 import LiteLLMManagedVectorStoreVectorStoreMetadataType0
from .lite_llm_managed_vector_stores_table import LiteLLMManagedVectorStoresTable
from .lite_llm_managed_vector_stores_table_litellm_params_type_0 import LiteLLMManagedVectorStoresTableLitellmParamsType0
from .lite_llm_managed_vector_stores_table_vector_store_metadata_type_0 import LiteLLMManagedVectorStoresTableVectorStoreMetadataType0
from .lite_llm_model_table import LiteLLMModelTable
from .lite_llm_model_table_model_aliases_type_0 import LiteLLMModelTableModelAliasesType0
from .lite_llm_object_permission_base import LiteLLMObjectPermissionBase
from .lite_llm_object_permission_base_mcp_tool_permissions_type_0 import LiteLLMObjectPermissionBaseMcpToolPermissionsType0
from .lite_llm_object_permission_table import LiteLLMObjectPermissionTable
from .lite_llm_object_permission_table_mcp_tool_permissions_type_0 import LiteLLMObjectPermissionTableMcpToolPermissionsType0
from .lite_llm_organization_membership_table import LiteLLMOrganizationMembershipTable
from .lite_llm_organization_table_with_members import LiteLLMOrganizationTableWithMembers
from .lite_llm_organization_table_with_members_metadata_type_0 import LiteLLMOrganizationTableWithMembersMetadataType0
from .lite_llm_params import LiteLLMParams
from .lite_llm_params_model_info_type_0 import LiteLLMParamsModelInfoType0
from .lite_llm_params_search_context_cost_per_query_type_0 import LiteLLMParamsSearchContextCostPerQueryType0
from .lite_llm_params_tiered_pricing_type_0_item import LiteLLMParamsTieredPricingType0Item
from .lite_llm_params_vertex_credentials_type_1 import LiteLLMParamsVertexCredentialsType1
from .lite_llm_spend_logs import LiteLLMSpendLogs
from .lite_llm_spend_logs_messages_type_2 import LiteLLMSpendLogsMessagesType2
from .lite_llm_spend_logs_response_type_2 import LiteLLMSpendLogsResponseType2
from .lite_llm_team_membership import LiteLLMTeamMembership
from .lite_llm_team_table import LiteLLMTeamTable
from .lite_llm_team_table_metadata_type_0 import LiteLLMTeamTableMetadataType0
from .lite_llm_team_table_router_settings_type_0 import LiteLLMTeamTableRouterSettingsType0
from .lite_llm_verification_token import LiteLLMVerificationToken
from .lite_llm_verification_token_aliases import LiteLLMVerificationTokenAliases
from .lite_llm_verification_token_config import LiteLLMVerificationTokenConfig
from .lite_llm_verification_token_litellm_budget_table_type_0 import LiteLLMVerificationTokenLitellmBudgetTableType0
from .lite_llm_verification_token_metadata import LiteLLMVerificationTokenMetadata
from .lite_llm_verification_token_model_max_budget import LiteLLMVerificationTokenModelMaxBudget
from .lite_llm_verification_token_model_spend import LiteLLMVerificationTokenModelSpend
from .lite_llm_verification_token_permissions import LiteLLMVerificationTokenPermissions
from .lite_llm_verification_token_router_settings_type_0 import LiteLLMVerificationTokenRouterSettingsType0
from .lite_llmmcp_server_table import LiteLLMMCPServerTable
from .lite_llmmcp_server_table_auth_type_type_0 import LiteLLMMCPServerTableAuthTypeType0
from .lite_llmmcp_server_table_env import LiteLLMMCPServerTableEnv
from .lite_llmmcp_server_table_mcp_info_type_0 import LiteLLMMCPServerTableMcpInfoType0
from .lite_llmmcp_server_table_static_headers_type_0 import LiteLLMMCPServerTableStaticHeadersType0
from .lite_llmmcp_server_table_status_type_0 import LiteLLMMCPServerTableStatusType0
from .lite_llmmcp_server_table_teams_item import LiteLLMMCPServerTableTeamsItem
from .lite_llmmcp_server_table_transport import LiteLLMMCPServerTableTransport
from .litellm_params import LitellmParams
from .litellm_params_additional_provider_specific_params_type_0 import LitellmParamsAdditionalProviderSpecificParamsType0
from .litellm_params_config_type_0 import LitellmParamsConfigType0
from .litellm_params_default_action import LitellmParamsDefaultAction
from .litellm_params_detect_secrets_config_type_0 import LitellmParamsDetectSecretsConfigType0
from .litellm_params_detectors_type_0 import LitellmParamsDetectorsType0
from .litellm_params_metadata_type_0 import LitellmParamsMetadataType0
from .litellm_params_mock_redacted_text_type_0 import LitellmParamsMockRedactedTextType0
from .litellm_params_on_disallowed_action import LitellmParamsOnDisallowedAction
from .litellm_params_on_flagged_type_0 import LitellmParamsOnFlaggedType0
from .litellm_params_pii_entities_config_type_0 import LitellmParamsPiiEntitiesConfigType0
from .litellm_params_presidio_filter_scope import LitellmParamsPresidioFilterScope
from .litellm_params_presidio_run_on_type_0 import LitellmParamsPresidioRunOnType0
from .litellm_params_presidio_score_thresholds_type_0 import LitellmParamsPresidioScoreThresholdsType0
from .litellm_user_roles import LitellmUserRoles
from .logging_callback_status import LoggingCallbackStatus
from .logging_callback_status_status import LoggingCallbackStatusStatus
from .make_agents_public_request import MakeAgentsPublicRequest
from .make_mcp_servers_public_request import MakeMCPServersPublicRequest
from .mcp_credentials import MCPCredentials
from .mcp_public_server import MCPPublicServer
from .mcp_public_server_auth_type_type_0 import MCPPublicServerAuthTypeType0
from .mcp_public_server_mcp_info_type_0 import MCPPublicServerMcpInfoType0
from .mcp_public_server_transport import MCPPublicServerTransport
from .member import Member
from .member_role import MemberRole
from .message import Message
from .message_provider_specific_fields_type_0 import MessageProviderSpecificFieldsType0
from .message_role import MessageRole
from .metric_with_metadata import MetricWithMetadata
from .metric_with_metadata_api_key_breakdown import MetricWithMetadataApiKeyBreakdown
from .metric_with_metadata_metadata import MetricWithMetadataMetadata
from .mode import Mode
from .mode_tags import ModeTags
from .model_info import ModelInfo
from .model_info_delete import ModelInfoDelete
from .model_info_tier_type_0 import ModelInfoTierType0
from .model_response import ModelResponse
from .mutual_tls_security_scheme import MutualTLSSecurityScheme
from .new_customer_request import NewCustomerRequest
from .new_customer_request_allowed_model_region_type_0 import NewCustomerRequestAllowedModelRegionType0
from .new_customer_request_model_max_budget_type_0 import NewCustomerRequestModelMaxBudgetType0
from .new_mcp_server_request import NewMCPServerRequest
from .new_mcp_server_request_auth_type_type_0 import NewMCPServerRequestAuthTypeType0
from .new_mcp_server_request_env import NewMCPServerRequestEnv
from .new_mcp_server_request_mcp_info_type_0 import NewMCPServerRequestMcpInfoType0
from .new_mcp_server_request_static_headers_type_0 import NewMCPServerRequestStaticHeadersType0
from .new_mcp_server_request_transport import NewMCPServerRequestTransport
from .new_model_group_request import NewModelGroupRequest
from .new_model_group_response import NewModelGroupResponse
from .new_organization_request import NewOrganizationRequest
from .new_organization_request_metadata_type_0 import NewOrganizationRequestMetadataType0
from .new_organization_request_model_max_budget_type_0 import NewOrganizationRequestModelMaxBudgetType0
from .new_organization_request_model_rpm_limit_type_0 import NewOrganizationRequestModelRpmLimitType0
from .new_organization_request_model_tpm_limit_type_0 import NewOrganizationRequestModelTpmLimitType0
from .new_organization_response import NewOrganizationResponse
from .new_organization_response_metadata_type_0 import NewOrganizationResponseMetadataType0
from .new_team_request import NewTeamRequest
from .new_team_request_metadata_type_0 import NewTeamRequestMetadataType0
from .new_team_request_model_aliases_type_0 import NewTeamRequestModelAliasesType0
from .new_team_request_model_rpm_limit_type_0 import NewTeamRequestModelRpmLimitType0
from .new_team_request_model_tpm_limit_type_0 import NewTeamRequestModelTpmLimitType0
from .new_team_request_router_settings_type_0 import NewTeamRequestRouterSettingsType0
from .new_team_request_rpm_limit_type_type_0 import NewTeamRequestRpmLimitTypeType0
from .new_team_request_secret_manager_settings_type_0 import NewTeamRequestSecretManagerSettingsType0
from .new_team_request_tpm_limit_type_type_0 import NewTeamRequestTpmLimitTypeType0
from .new_user_request_team import NewUserRequestTeam
from .new_user_request_team_user_role import NewUserRequestTeamUserRole
from .o_auth_2_security_scheme import OAuth2SecurityScheme
from .o_auth_flows import OAuthFlows
from .o_auth_flows_authorization_code_type_0 import OAuthFlowsAuthorizationCodeType0
from .o_auth_flows_client_credentials_type_0 import OAuthFlowsClientCredentialsType0
from .o_auth_flows_implicit_type_0 import OAuthFlowsImplicitType0
from .o_auth_flows_password_type_0 import OAuthFlowsPasswordType0
from .open_id_connect_security_scheme import OpenIdConnectSecurityScheme
from .org_member import OrgMember
from .org_member_role import OrgMemberRole
from .organization_member_add_request import OrganizationMemberAddRequest
from .organization_member_delete_request import OrganizationMemberDeleteRequest
from .organization_member_update_request import OrganizationMemberUpdateRequest
from .organization_request import OrganizationRequest
from .paginated_audit_log_response import PaginatedAuditLogResponse
from .pass_through_endpoint_response import PassThroughEndpointResponse
from .pass_through_generic_endpoint import PassThroughGenericEndpoint
from .pass_through_generic_endpoint_guardrails_type_0 import PassThroughGenericEndpointGuardrailsType0
from .pass_through_generic_endpoint_headers import PassThroughGenericEndpointHeaders
from .pass_through_guardrail_settings import PassThroughGuardrailSettings
from .patch_agent_request import PatchAgentRequest
from .patch_agent_request_litellm_params import PatchAgentRequestLitellmParams
from .patch_guardrail_request import PatchGuardrailRequest
from .patch_guardrail_request_guardrail_info_type_0 import PatchGuardrailRequestGuardrailInfoType0
from .patch_prompt_request import PatchPromptRequest
from .per_user_analytics_response import PerUserAnalyticsResponse
from .per_user_metrics import PerUserMetrics
from .pii_action import PiiAction
from .pii_entity_type import PiiEntityType
from .prompt import Prompt
from .prompt_info import PromptInfo
from .prompt_info_prompt_type import PromptInfoPromptType
from .prompt_info_response import PromptInfoResponse
from .prompt_lite_llm_params import PromptLiteLLMParams
from .prompt_lite_llm_params_provider_specific_query_params_type_0 import PromptLiteLLMParamsProviderSpecificQueryParamsType0
from .prompt_spec import PromptSpec
from .prompt_template_base import PromptTemplateBase
from .prompt_template_base_metadata_type_0 import PromptTemplateBaseMetadataType0
from .prompt_tokens_details import PromptTokensDetails
from .prompt_tokens_details_modality import PromptTokensDetailsModality
from .provider_budget_response import ProviderBudgetResponse
from .provider_budget_response_object import ProviderBudgetResponseObject
from .provider_budget_response_providers import ProviderBudgetResponseProviders
from .provider_create_info import ProviderCreateInfo
from .provider_credential_field import ProviderCredentialField
from .provider_credential_field_field_type import ProviderCredentialFieldFieldType
from .proxy_chat_completion_request import ProxyChatCompletionRequest
from .proxy_chat_completion_request_context_window_fallback_dict_type_0 import ProxyChatCompletionRequestContextWindowFallbackDictType0
from .proxy_chat_completion_request_function_call_type_1 import ProxyChatCompletionRequestFunctionCallType1
from .proxy_chat_completion_request_functions_type_0_item import ProxyChatCompletionRequestFunctionsType0Item
from .proxy_chat_completion_request_logit_bias_type_0 import ProxyChatCompletionRequestLogitBiasType0
from .proxy_chat_completion_request_metadata_type_0 import ProxyChatCompletionRequestMetadataType0
from .proxy_chat_completion_request_response_format_type_0 import ProxyChatCompletionRequestResponseFormatType0
from .proxy_chat_completion_request_stream_options_type_0 import ProxyChatCompletionRequestStreamOptionsType0
from .proxy_chat_completion_request_tool_choice_type_1 import ProxyChatCompletionRequestToolChoiceType1
from .proxy_chat_completion_request_tools_type_0_item import ProxyChatCompletionRequestToolsType0Item
from .public_model_hub_info import PublicModelHubInfo
from .public_model_hub_info_useful_links_type_0 import PublicModelHubInfoUsefulLinksType0
from .public_model_hub_info_useful_links_type_0_additional_property_type_1 import PublicModelHubInfoUsefulLinksType0AdditionalPropertyType1
from .raw_request_typed_dict import RawRequestTypedDict
from .raw_request_typed_dict_raw_request_body_type_0 import RawRequestTypedDictRawRequestBodyType0
from .raw_request_typed_dict_raw_request_headers_type_0 import RawRequestTypedDictRawRequestHeadersType0
from .response_lite_llm_managed_vector_store import ResponseLiteLLMManagedVectorStore
from .retrieve_fine_tuning_job_fine_tuning_jobs_fine_tuning_job_id_get_custom_llm_provider_type_0 import RetrieveFineTuningJobFineTuningJobsFineTuningJobIdGetCustomLlmProviderType0
from .retrieve_fine_tuning_job_v1_fine_tuning_jobs_fine_tuning_job_id_get_custom_llm_provider_type_0 import RetrieveFineTuningJobV1FineTuningJobsFineTuningJobIdGetCustomLlmProviderType0
from .role_mappings import RoleMappings
from .role_mappings_roles import RoleMappingsRoles
from .router_fields_response import RouterFieldsResponse
from .router_fields_response_routing_strategy_descriptions import RouterFieldsResponseRoutingStrategyDescriptions
from .router_settings_field import RouterSettingsField
from .router_settings_response import RouterSettingsResponse
from .router_settings_response_current_values import RouterSettingsResponseCurrentValues
from .router_settings_response_routing_strategy_descriptions import RouterSettingsResponseRoutingStrategyDescriptions
from .scim_feature import SCIMFeature
from .scim_group import SCIMGroup
from .scim_group_meta_type_0 import SCIMGroupMetaType0
from .scim_list_response import SCIMListResponse
from .scim_member import SCIMMember
from .scim_patch_op import SCIMPatchOp
from .scim_patch_operation import SCIMPatchOperation
from .scim_service_provider_config import SCIMServiceProviderConfig
from .scim_service_provider_config_authentication_schemes_type_0_item import SCIMServiceProviderConfigAuthenticationSchemesType0Item
from .scim_service_provider_config_meta_type_0 import SCIMServiceProviderConfigMetaType0
from .scim_user import SCIMUser
from .scim_user_email import SCIMUserEmail
from .scim_user_group import SCIMUserGroup
from .scim_user_meta_type_0 import SCIMUserMetaType0
from .scim_user_name import SCIMUserName
from .search_tool import SearchTool
from .search_tool_info_response import SearchToolInfoResponse
from .search_tool_info_response_litellm_params import SearchToolInfoResponseLitellmParams
from .search_tool_info_response_search_tool_info_type_0 import SearchToolInfoResponseSearchToolInfoType0
from .search_tool_lite_llm_params import SearchToolLiteLLMParams
from .search_tool_search_tool_info_type_0 import SearchToolSearchToolInfoType0
from .skill import Skill
from .spend_analytics_paginated_response import SpendAnalyticsPaginatedResponse
from .spend_calculate_request import SpendCalculateRequest
from .spend_calculate_request_completion_response_type_0 import SpendCalculateRequestCompletionResponseType0
from .spend_metrics import SpendMetrics
from .sso_config import SSOConfig
from .sso_settings_response import SSOSettingsResponse
from .sso_settings_response_field_schema import SSOSettingsResponseFieldSchema
from .sso_settings_response_values import SSOSettingsResponseValues
from .streaming_choices import StreamingChoices
from .tag_active_users_response import TagActiveUsersResponse
from .tag_delete_request import TagDeleteRequest
from .tag_info_request import TagInfoRequest
from .tag_new_request import TagNewRequest
from .tag_new_request_model_info_type_0 import TagNewRequestModelInfoType0
from .tag_new_request_model_max_budget_type_0 import TagNewRequestModelMaxBudgetType0
from .tag_summary_metrics import TagSummaryMetrics
from .tag_summary_response import TagSummaryResponse
from .tag_update_request import TagUpdateRequest
from .tag_update_request_model_info_type_0 import TagUpdateRequestModelInfoType0
from .tag_update_request_model_max_budget_type_0 import TagUpdateRequestModelMaxBudgetType0
from .team_add_member_response_metadata_type_0 import TeamAddMemberResponseMetadataType0
from .team_add_member_response_router_settings_type_0 import TeamAddMemberResponseRouterSettingsType0
from .team_list_response import TeamListResponse
from .team_member_add_request import TeamMemberAddRequest
from .team_member_add_result import TeamMemberAddResult
from .team_member_add_result_updated_team_membership_type_0 import TeamMemberAddResultUpdatedTeamMembershipType0
from .team_member_add_result_updated_user_type_0 import TeamMemberAddResultUpdatedUserType0
from .team_member_delete_request import TeamMemberDeleteRequest
from .team_member_update_request import TeamMemberUpdateRequest
from .team_member_update_request_role_type_0 import TeamMemberUpdateRequestRoleType0
from .team_member_update_response import TeamMemberUpdateResponse
from .team_model_add_request import TeamModelAddRequest
from .team_model_delete_request import TeamModelDeleteRequest
from .test_prompt_request import TestPromptRequest
from .test_prompt_request_conversation_history_type_0_item import TestPromptRequestConversationHistoryType0Item
from .test_prompt_request_prompt_variables_type_0 import TestPromptRequestPromptVariablesType0
from .test_search_tool_connection_request import TestSearchToolConnectionRequest
from .test_search_tool_connection_request_litellm_params import TestSearchToolConnectionRequestLitellmParams
from .token_count_details_response import TokenCountDetailsResponse
from .token_count_request import TokenCountRequest
from .token_count_request_contents_type_0_item import TokenCountRequestContentsType0Item
from .token_count_request_messages_type_0_item import TokenCountRequestMessagesType0Item
from .token_count_response import TokenCountResponse
from .token_count_response_original_response_type_0 import TokenCountResponseOriginalResponseType0
from .tool_permission_rule import ToolPermissionRule
from .tool_permission_rule_allowed_param_patterns_type_0 import ToolPermissionRuleAllowedParamPatternsType0
from .tool_permission_rule_decision import ToolPermissionRuleDecision
from .top_logprob import TopLogprob
from .transform_request_body import TransformRequestBody
from .transform_request_body_request_body import TransformRequestBodyRequestBody
from .ui_discovery_endpoints import UiDiscoveryEndpoints
from .ui_settings import UISettings
from .ui_settings_response import UISettingsResponse
from .ui_settings_response_field_schema import UISettingsResponseFieldSchema
from .ui_settings_response_values import UISettingsResponseValues
from .ui_theme_config import UIThemeConfig
from .ui_theme_settings_response import UIThemeSettingsResponse
from .ui_theme_settings_response_field_schema import UIThemeSettingsResponseFieldSchema
from .ui_theme_settings_response_values import UIThemeSettingsResponseValues
from .ui_view_spend_logs_spend_logs_v2_get_response_200_ui_view_spend_logs_spend_logs_v2_get import UiViewSpendLogsSpendLogsV2GetResponse200UiViewSpendLogsSpendLogsV2Get
from .update_cost_discount_config_config_cost_discount_config_patch_cost_discount_config import UpdateCostDiscountConfigConfigCostDiscountConfigPatchCostDiscountConfig
from .update_cost_margin_config_config_cost_margin_config_patch_cost_margin_config import UpdateCostMarginConfigConfigCostMarginConfigPatchCostMarginConfig
from .update_cost_margin_config_config_cost_margin_config_patch_cost_margin_config_additional_property_type_1 import UpdateCostMarginConfigConfigCostMarginConfigPatchCostMarginConfigAdditionalPropertyType1
from .update_customer_request import UpdateCustomerRequest
from .update_customer_request_allowed_model_region_type_0 import UpdateCustomerRequestAllowedModelRegionType0
from .update_deployment import UpdateDeployment
from .update_guardrail_request import UpdateGuardrailRequest
from .update_lite_llm_params import UpdateLiteLLMParams
from .update_lite_llm_params_model_info_type_0 import UpdateLiteLLMParamsModelInfoType0
from .update_lite_llm_params_search_context_cost_per_query_type_0 import UpdateLiteLLMParamsSearchContextCostPerQueryType0
from .update_lite_llm_params_tiered_pricing_type_0_item import UpdateLiteLLMParamsTieredPricingType0Item
from .update_lite_llm_params_vertex_credentials_type_1 import UpdateLiteLLMParamsVertexCredentialsType1
from .update_mcp_server_request import UpdateMCPServerRequest
from .update_mcp_server_request_auth_type_type_0 import UpdateMCPServerRequestAuthTypeType0
from .update_mcp_server_request_env import UpdateMCPServerRequestEnv
from .update_mcp_server_request_mcp_info_type_0 import UpdateMCPServerRequestMcpInfoType0
from .update_mcp_server_request_static_headers_type_0 import UpdateMCPServerRequestStaticHeadersType0
from .update_mcp_server_request_transport import UpdateMCPServerRequestTransport
from .update_model_group_request import UpdateModelGroupRequest
from .update_public_model_groups_request import UpdatePublicModelGroupsRequest
from .update_search_tool_request import UpdateSearchToolRequest
from .update_team_member_permissions_request import UpdateTeamMemberPermissionsRequest
from .update_team_request import UpdateTeamRequest
from .update_team_request_metadata_type_0 import UpdateTeamRequestMetadataType0
from .update_team_request_model_aliases_type_0 import UpdateTeamRequestModelAliasesType0
from .update_team_request_model_rpm_limit_type_0 import UpdateTeamRequestModelRpmLimitType0
from .update_team_request_model_tpm_limit_type_0 import UpdateTeamRequestModelTpmLimitType0
from .update_team_request_router_settings_type_0 import UpdateTeamRequestRouterSettingsType0
from .update_team_request_secret_manager_settings_type_0 import UpdateTeamRequestSecretManagerSettingsType0
from .update_useful_links_request import UpdateUsefulLinksRequest
from .update_useful_links_request_useful_links import UpdateUsefulLinksRequestUsefulLinks
from .update_useful_links_request_useful_links_additional_property_type_1 import UpdateUsefulLinksRequestUsefulLinksAdditionalPropertyType1
from .user_api_key_auth import UserAPIKeyAuth
from .user_api_key_auth_aliases import UserAPIKeyAuthAliases
from .user_api_key_auth_allowed_model_region_type_0 import UserAPIKeyAuthAllowedModelRegionType0
from .user_api_key_auth_config import UserAPIKeyAuthConfig
from .user_api_key_auth_litellm_budget_table_type_0 import UserAPIKeyAuthLitellmBudgetTableType0
from .user_api_key_auth_metadata import UserAPIKeyAuthMetadata
from .user_api_key_auth_model_max_budget import UserAPIKeyAuthModelMaxBudget
from .user_api_key_auth_model_spend import UserAPIKeyAuthModelSpend
from .user_api_key_auth_organization_metadata_type_0 import UserAPIKeyAuthOrganizationMetadataType0
from .user_api_key_auth_permissions import UserAPIKeyAuthPermissions
from .user_api_key_auth_router_settings_type_0 import UserAPIKeyAuthRouterSettingsType0
from .user_api_key_auth_rpm_limit_per_model_type_0 import UserAPIKeyAuthRpmLimitPerModelType0
from .user_api_key_auth_team_metadata_type_0 import UserAPIKeyAuthTeamMetadataType0
from .user_api_key_auth_team_model_aliases_type_0 import UserAPIKeyAuthTeamModelAliasesType0
from .user_api_key_auth_tpm_limit_per_model_type_0 import UserAPIKeyAuthTpmLimitPerModelType0
from .user_update_result import UserUpdateResult
from .user_update_result_updated_user_type_0 import UserUpdateResultUpdatedUserType0
from .validate_blocked_words_file_guardrails_validate_blocked_words_file_post_request import ValidateBlockedWordsFileGuardrailsValidateBlockedWordsFilePostRequest
from .validation_error import ValidationError
from .vector_store_delete_request import VectorStoreDeleteRequest
from .vector_store_info_request import VectorStoreInfoRequest
from .vector_store_update_request import VectorStoreUpdateRequest
from .vector_store_update_request_vector_store_metadata_type_0 import VectorStoreUpdateRequestVectorStoreMetadataType0

__all__ = (
    "AccessControlUIAccessMode",
    "AccessGroupInfo",
    "ActiveUsersAnalyticsResponse",
    "AddTeamCallback",
    "AddTeamCallbackCallbackTypeType0",
    "AddTeamCallbackCallbackVars",
    "AgentCapabilities",
    "AgentCard",
    "AgentCardSecuritySchemesType0",
    "AgentCardSecurityType0Item",
    "AgentCardSignature",
    "AgentCardSignatureHeaderType0",
    "AgentConfig",
    "AgentConfigLitellmParams",
    "AgentCreateInfo",
    "AgentCreateInfoLitellmParamsTemplateType0",
    "AgentCredentialField",
    "AgentCredentialFieldFieldType",
    "AgentExtension",
    "AgentExtensionParamsType0",
    "AgentInterface",
    "AgentMakePublicResponse",
    "AgentProvider",
    "AgentResponse",
    "AgentResponseAgentCardParams",
    "AgentResponseLitellmParamsType0",
    "AgentSkill",
    "AgentSkillSecurityType0Item",
    "AllowedVectorStoreIndexItem",
    "AllowedVectorStoreIndexItemIndexPermissionsItem",
    "APIKeySecurityScheme",
    "APIKeySecuritySchemeIn",
    "ApplyGuardrailRequest",
    "ApplyGuardrailResponse",
    "AuditLogResponse",
    "AuditLogResponseBeforeValueType0",
    "AuditLogResponseUpdatedValuesType0",
    "BaseLitellmParams",
    "BaseLitellmParamsAdditionalProviderSpecificParamsType0",
    "BaseLitellmParamsDetectSecretsConfigType0",
    "BlockedWord",
    "BlockKeyRequest",
    "BlockTeamRequest",
    "BlockUsers",
    "BodyAudioTranscriptionsAudioTranscriptionsPost",
    "BodyAudioTranscriptionsV1AudioTranscriptionsPost",
    "BodyConvertPromptFileToJsonUtilsDotpromptJsonConverterPost",
    "BodyCreateFileFilesPost",
    "BodyCreateFileProviderV1FilesPost",
    "BodyCreateFileV1FilesPost",
    "BodyTestModelConnectionHealthTestConnectionPost",
    "BodyTestModelConnectionHealthTestConnectionPostLitellmParams",
    "BodyTestModelConnectionHealthTestConnectionPostModelInfo",
    "BodyTestModelConnectionHealthTestConnectionPostModeType0",
    "BodyTokenEndpointMcpServerNameTokenPost",
    "BodyTokenEndpointTokenPost",
    "BodyUploadLogoUploadLogoPost",
    "BodyVideoGenerationV1VideosPost",
    "BodyVideoGenerationVideosPost",
    "BreakdownMetrics",
    "BreakdownMetricsApiKeys",
    "BreakdownMetricsEndpoints",
    "BreakdownMetricsEntities",
    "BreakdownMetricsMcpServers",
    "BreakdownMetricsModelGroups",
    "BreakdownMetricsModels",
    "BreakdownMetricsProviders",
    "BudgetConfig",
    "BudgetDeleteRequest",
    "BudgetNewRequest",
    "BudgetNewRequestModelMaxBudgetType0",
    "BudgetRequest",
    "BulkTeamMemberAddRequest",
    "BulkTeamMemberAddResponse",
    "BulkTeamMemberAddResponseUpdatedTeamType0",
    "BulkUpdateUserRequest",
    "BulkUpdateUserResponse",
    "CachePingResponse",
    "CachePingResponseHealthCheckCacheParamsType0",
    "CacheSettingsField",
    "CacheSettingsResponse",
    "CacheSettingsResponseCurrentValues",
    "CacheSettingsResponseRedisTypeDescriptions",
    "CacheSettingsUpdateRequest",
    "CacheSettingsUpdateRequestCacheSettings",
    "CacheTestRequest",
    "CacheTestRequestCacheSettings",
    "CacheTestResponse",
    "CallbacksByType",
    "CallTypes",
    "ChatCompletionAnnotation",
    "ChatCompletionAnnotationURLCitation",
    "ChatCompletionAssistantMessage",
    "ChatCompletionAssistantToolCall",
    "ChatCompletionAudioObject",
    "ChatCompletionAudioResponse",
    "ChatCompletionCachedContent",
    "ChatCompletionChatCompletionsPostBody",
    "ChatCompletionChatCompletionsPostBodyContextWindowFallbackDictType0",
    "ChatCompletionChatCompletionsPostBodyFunctionCallType1",
    "ChatCompletionChatCompletionsPostBodyFunctionsType0Item",
    "ChatCompletionChatCompletionsPostBodyLogitBiasType0",
    "ChatCompletionChatCompletionsPostBodyMetadataType0",
    "ChatCompletionChatCompletionsPostBodyResponseFormatType0",
    "ChatCompletionChatCompletionsPostBodyStreamOptionsType0",
    "ChatCompletionChatCompletionsPostBodyToolChoiceType1",
    "ChatCompletionChatCompletionsPostBodyToolsType0Item",
    "ChatCompletionDeveloperMessage",
    "ChatCompletionDocumentObject",
    "ChatCompletionFileObject",
    "ChatCompletionFileObjectFile",
    "ChatCompletionFunctionMessage",
    "ChatCompletionImageObject",
    "ChatCompletionImageUrlObject",
    "ChatCompletionMessageToolCall",
    "ChatCompletionRedactedThinkingBlock",
    "ChatCompletionRedactedThinkingBlockCacheControlType0",
    "ChatCompletionSystemMessage",
    "ChatCompletionTextObject",
    "ChatCompletionThinkingBlock",
    "ChatCompletionThinkingBlockCacheControlType0",
    "ChatCompletionTokenLogprob",
    "ChatCompletionToolCallFunctionChunk",
    "ChatCompletionToolCallFunctionChunkProviderSpecificFieldsType0",
    "ChatCompletionToolMessage",
    "ChatCompletionUserMessage",
    "ChatCompletionV1ChatCompletionsPostBody",
    "ChatCompletionV1ChatCompletionsPostBodyContextWindowFallbackDictType0",
    "ChatCompletionV1ChatCompletionsPostBodyFunctionCallType1",
    "ChatCompletionV1ChatCompletionsPostBodyFunctionsType0Item",
    "ChatCompletionV1ChatCompletionsPostBodyLogitBiasType0",
    "ChatCompletionV1ChatCompletionsPostBodyMetadataType0",
    "ChatCompletionV1ChatCompletionsPostBodyResponseFormatType0",
    "ChatCompletionV1ChatCompletionsPostBodyStreamOptionsType0",
    "ChatCompletionV1ChatCompletionsPostBodyToolChoiceType1",
    "ChatCompletionV1ChatCompletionsPostBodyToolsType0Item",
    "ChatCompletionVideoObject",
    "ChatCompletionVideoUrlObject",
    "ChoiceLogprobs",
    "Choices",
    "ChoicesProviderSpecificFieldsType0",
    "CitationsObject",
    "CloudZeroExportRequest",
    "CloudZeroExportResponse",
    "CloudZeroExportResponseDryRunDataType0",
    "CloudZeroExportResponseSummaryType0",
    "CloudZeroInitRequest",
    "CloudZeroInitResponse",
    "CloudZeroSettingsUpdate",
    "CloudZeroSettingsView",
    "ConfigurableClientsideParamsCustomAuth",
    "ContentFilterAction",
    "ContentFilterPattern",
    "ContentFilterPatternPatternType",
    "ConvertPromptFileToJsonUtilsDotpromptJsonConverterPostResponseConvertPromptFileToJsonUtilsDotpromptJsonConverterPost",
    "CostEstimateRequest",
    "CostEstimateResponse",
    "CreateCredentialItem",
    "CreateCredentialItemCredentialInfo",
    "CreateCredentialItemCredentialValuesType0",
    "CreateGuardrailRequest",
    "CreateSearchToolRequest",
    "CredentialItem",
    "CredentialItemCredentialInfo",
    "CredentialItemCredentialValues",
    "DailySpendData",
    "DailySpendMetadata",
    "DefaultInternalUserParams",
    "DefaultInternalUserParamsUserRoleType0",
    "DefaultTeamSettingsResponse",
    "DefaultTeamSettingsResponseFieldSchema",
    "DefaultTeamSettingsResponseValues",
    "DefaultTeamSSOParams",
    "DeleteCustomerRequest",
    "DeleteFallbackFallbackModelDeleteFallbackType",
    "DeleteModelGroupResponse",
    "DeleteOrganizationRequest",
    "DeleteSkillResponse",
    "DeleteTeamRequest",
    "DeleteUserRequest",
    "Deployment",
    "DistinctTagResponse",
    "DistinctTagsResponse",
    "DocumentObject",
    "EmailEvent",
    "EmailEventSettings",
    "EmailEventSettingsResponse",
    "EmailEventSettingsUpdateRequest",
    "EmbeddingRequest",
    "EmbeddingRequestCustomLlmProviderType1",
    "EmbeddingRequestLitellmLoggingObjType0",
    "EmbeddingsEmbeddingsPostBody",
    "EmbeddingsEmbeddingsPostBodyCustomLlmProviderType1",
    "EmbeddingsEmbeddingsPostBodyLitellmLoggingObjType0",
    "EmbeddingsV1EmbeddingsPostBody",
    "EmbeddingsV1EmbeddingsPostBodyCustomLlmProviderType1",
    "EmbeddingsV1EmbeddingsPostBodyLitellmLoggingObjType0",
    "ErrorResponse",
    "ErrorResponseDetail",
    "FallbackCreateRequest",
    "FallbackCreateRequestFallbackType",
    "FallbackDeleteResponse",
    "FallbackGetResponse",
    "FallbackResponse",
    "FunctionCall",
    "GetFallbackFallbackModelGetFallbackType",
    "GetGlobalSpendReportGlobalSpendReportGetGroupByType0",
    "GetTeamMemberPermissionsResponse",
    "GraySwanGuardrailConfigModelOptionalParams",
    "GraySwanGuardrailConfigModelOptionalParamsCategoriesType0",
    "Guardrail",
    "GUARDRAILDEFINITIONLOCATION",
    "GuardrailGuardrailInfoType0",
    "GuardrailInfoResponse",
    "GuardrailInfoResponseGuardrailInfoType0",
    "HealthServicesEndpointHealthServicesGetServiceType0",
    "HTTPAuthSecurityScheme",
    "HTTPValidationError",
    "Hyperparameters",
    "ImageURLListItem",
    "ImageURLObject",
    "IndexCreateLiteLLMParams",
    "IndexCreateRequest",
    "IndexCreateRequestIndexInfoType0",
    "InputAudio",
    "InputAudioFormat",
    "InternalUserSettingsResponse",
    "InternalUserSettingsResponseFieldSchema",
    "InternalUserSettingsResponseValues",
    "IPAddress",
    "KeyAliasesKeyAliasesGetResponseKeyAliasesKeyAliasesGet",
    "KeyHealthResponse",
    "KeyHealthResponseKey",
    "KeyListResponseObject",
    "KeyMetadata",
    "KeyMetricWithMetadata",
    "KeyRequest",
    "LakeraCategoryThresholds",
    "ListAccessGroupsResponse",
    "ListFineTuningJobsFineTuningJobsGetCustomLlmProviderType0",
    "ListFineTuningJobsV1FineTuningJobsGetCustomLlmProviderType0",
    "ListGuardrailsResponse",
    "ListPromptsResponse",
    "ListSearchToolsResponse",
    "ListSkillsResponse",
    "ListToolRestApiMcpRestToolsListGetResponseListToolRestApiMcpRestToolsListGet",
    "LiteLLMBudgetTable",
    "LiteLLMBudgetTableModelMaxBudgetType0",
    "LiteLLMDeletedTeamTable",
    "LiteLLMDeletedTeamTableMetadataType0",
    "LiteLLMDeletedTeamTableRouterSettingsType0",
    "LiteLLMDeletedVerificationToken",
    "LiteLLMDeletedVerificationTokenAliases",
    "LiteLLMDeletedVerificationTokenConfig",
    "LiteLLMDeletedVerificationTokenLitellmBudgetTableType0",
    "LiteLLMDeletedVerificationTokenMetadata",
    "LiteLLMDeletedVerificationTokenModelMaxBudget",
    "LiteLLMDeletedVerificationTokenModelSpend",
    "LiteLLMDeletedVerificationTokenPermissions",
    "LiteLLMDeletedVerificationTokenRouterSettingsType0",
    "LiteLLMEndUserTable",
    "LiteLLMEndUserTableAllowedModelRegionType0",
    "LiteLLMFineTuningJobCreate",
    "LiteLLMFineTuningJobCreateCustomLlmProviderType0",
    "LiteLLMKeyType",
    "LiteLLMManagedVectorStore",
    "LiteLLMManagedVectorStoreListResponse",
    "LiteLLMManagedVectorStoreLitellmParamsType0",
    "LiteLLMManagedVectorStoresTable",
    "LiteLLMManagedVectorStoresTableLitellmParamsType0",
    "LiteLLMManagedVectorStoresTableVectorStoreMetadataType0",
    "LiteLLMManagedVectorStoreVectorStoreMetadataType0",
    "LiteLLMMCPServerTable",
    "LiteLLMMCPServerTableAuthTypeType0",
    "LiteLLMMCPServerTableEnv",
    "LiteLLMMCPServerTableMcpInfoType0",
    "LiteLLMMCPServerTableStaticHeadersType0",
    "LiteLLMMCPServerTableStatusType0",
    "LiteLLMMCPServerTableTeamsItem",
    "LiteLLMMCPServerTableTransport",
    "LiteLLMModelTable",
    "LiteLLMModelTableModelAliasesType0",
    "LiteLLMObjectPermissionBase",
    "LiteLLMObjectPermissionBaseMcpToolPermissionsType0",
    "LiteLLMObjectPermissionTable",
    "LiteLLMObjectPermissionTableMcpToolPermissionsType0",
    "LiteLLMOrganizationMembershipTable",
    "LiteLLMOrganizationTableWithMembers",
    "LiteLLMOrganizationTableWithMembersMetadataType0",
    "LiteLLMParams",
    "LitellmParams",
    "LitellmParamsAdditionalProviderSpecificParamsType0",
    "LitellmParamsConfigType0",
    "LitellmParamsDefaultAction",
    "LitellmParamsDetectorsType0",
    "LitellmParamsDetectSecretsConfigType0",
    "LitellmParamsMetadataType0",
    "LitellmParamsMockRedactedTextType0",
    "LiteLLMParamsModelInfoType0",
    "LitellmParamsOnDisallowedAction",
    "LitellmParamsOnFlaggedType0",
    "LitellmParamsPiiEntitiesConfigType0",
    "LitellmParamsPresidioFilterScope",
    "LitellmParamsPresidioRunOnType0",
    "LitellmParamsPresidioScoreThresholdsType0",
    "LiteLLMParamsSearchContextCostPerQueryType0",
    "LiteLLMParamsTieredPricingType0Item",
    "LiteLLMParamsVertexCredentialsType1",
    "LiteLLMSpendLogs",
    "LiteLLMSpendLogsMessagesType2",
    "LiteLLMSpendLogsResponseType2",
    "LiteLLMTeamMembership",
    "LiteLLMTeamTable",
    "LiteLLMTeamTableMetadataType0",
    "LiteLLMTeamTableRouterSettingsType0",
    "LitellmUserRoles",
    "LiteLLMVerificationToken",
    "LiteLLMVerificationTokenAliases",
    "LiteLLMVerificationTokenConfig",
    "LiteLLMVerificationTokenLitellmBudgetTableType0",
    "LiteLLMVerificationTokenMetadata",
    "LiteLLMVerificationTokenModelMaxBudget",
    "LiteLLMVerificationTokenModelSpend",
    "LiteLLMVerificationTokenPermissions",
    "LiteLLMVerificationTokenRouterSettingsType0",
    "LoggingCallbackStatus",
    "LoggingCallbackStatusStatus",
    "MakeAgentsPublicRequest",
    "MakeMCPServersPublicRequest",
    "MCPCredentials",
    "MCPPublicServer",
    "MCPPublicServerAuthTypeType0",
    "MCPPublicServerMcpInfoType0",
    "MCPPublicServerTransport",
    "Member",
    "MemberRole",
    "Message",
    "MessageProviderSpecificFieldsType0",
    "MessageRole",
    "MetricWithMetadata",
    "MetricWithMetadataApiKeyBreakdown",
    "MetricWithMetadataMetadata",
    "Mode",
    "ModelInfo",
    "ModelInfoDelete",
    "ModelInfoTierType0",
    "ModelResponse",
    "ModeTags",
    "MutualTLSSecurityScheme",
    "NewCustomerRequest",
    "NewCustomerRequestAllowedModelRegionType0",
    "NewCustomerRequestModelMaxBudgetType0",
    "NewMCPServerRequest",
    "NewMCPServerRequestAuthTypeType0",
    "NewMCPServerRequestEnv",
    "NewMCPServerRequestMcpInfoType0",
    "NewMCPServerRequestStaticHeadersType0",
    "NewMCPServerRequestTransport",
    "NewModelGroupRequest",
    "NewModelGroupResponse",
    "NewOrganizationRequest",
    "NewOrganizationRequestMetadataType0",
    "NewOrganizationRequestModelMaxBudgetType0",
    "NewOrganizationRequestModelRpmLimitType0",
    "NewOrganizationRequestModelTpmLimitType0",
    "NewOrganizationResponse",
    "NewOrganizationResponseMetadataType0",
    "NewTeamRequest",
    "NewTeamRequestMetadataType0",
    "NewTeamRequestModelAliasesType0",
    "NewTeamRequestModelRpmLimitType0",
    "NewTeamRequestModelTpmLimitType0",
    "NewTeamRequestRouterSettingsType0",
    "NewTeamRequestRpmLimitTypeType0",
    "NewTeamRequestSecretManagerSettingsType0",
    "NewTeamRequestTpmLimitTypeType0",
    "NewUserRequestTeam",
    "NewUserRequestTeamUserRole",
    "OAuth2SecurityScheme",
    "OAuthFlows",
    "OAuthFlowsAuthorizationCodeType0",
    "OAuthFlowsClientCredentialsType0",
    "OAuthFlowsImplicitType0",
    "OAuthFlowsPasswordType0",
    "OpenIdConnectSecurityScheme",
    "OrganizationMemberAddRequest",
    "OrganizationMemberDeleteRequest",
    "OrganizationMemberUpdateRequest",
    "OrganizationRequest",
    "OrgMember",
    "OrgMemberRole",
    "PaginatedAuditLogResponse",
    "PassThroughEndpointResponse",
    "PassThroughGenericEndpoint",
    "PassThroughGenericEndpointGuardrailsType0",
    "PassThroughGenericEndpointHeaders",
    "PassThroughGuardrailSettings",
    "PatchAgentRequest",
    "PatchAgentRequestLitellmParams",
    "PatchGuardrailRequest",
    "PatchGuardrailRequestGuardrailInfoType0",
    "PatchPromptRequest",
    "PerUserAnalyticsResponse",
    "PerUserMetrics",
    "PiiAction",
    "PiiEntityType",
    "Prompt",
    "PromptInfo",
    "PromptInfoPromptType",
    "PromptInfoResponse",
    "PromptLiteLLMParams",
    "PromptLiteLLMParamsProviderSpecificQueryParamsType0",
    "PromptSpec",
    "PromptTemplateBase",
    "PromptTemplateBaseMetadataType0",
    "PromptTokensDetails",
    "PromptTokensDetailsModality",
    "ProviderBudgetResponse",
    "ProviderBudgetResponseObject",
    "ProviderBudgetResponseProviders",
    "ProviderCreateInfo",
    "ProviderCredentialField",
    "ProviderCredentialFieldFieldType",
    "ProxyChatCompletionRequest",
    "ProxyChatCompletionRequestContextWindowFallbackDictType0",
    "ProxyChatCompletionRequestFunctionCallType1",
    "ProxyChatCompletionRequestFunctionsType0Item",
    "ProxyChatCompletionRequestLogitBiasType0",
    "ProxyChatCompletionRequestMetadataType0",
    "ProxyChatCompletionRequestResponseFormatType0",
    "ProxyChatCompletionRequestStreamOptionsType0",
    "ProxyChatCompletionRequestToolChoiceType1",
    "ProxyChatCompletionRequestToolsType0Item",
    "PublicModelHubInfo",
    "PublicModelHubInfoUsefulLinksType0",
    "PublicModelHubInfoUsefulLinksType0AdditionalPropertyType1",
    "RawRequestTypedDict",
    "RawRequestTypedDictRawRequestBodyType0",
    "RawRequestTypedDictRawRequestHeadersType0",
    "ResponseLiteLLMManagedVectorStore",
    "RetrieveFineTuningJobFineTuningJobsFineTuningJobIdGetCustomLlmProviderType0",
    "RetrieveFineTuningJobV1FineTuningJobsFineTuningJobIdGetCustomLlmProviderType0",
    "RoleMappings",
    "RoleMappingsRoles",
    "RouterFieldsResponse",
    "RouterFieldsResponseRoutingStrategyDescriptions",
    "RouterSettingsField",
    "RouterSettingsResponse",
    "RouterSettingsResponseCurrentValues",
    "RouterSettingsResponseRoutingStrategyDescriptions",
    "SCIMFeature",
    "SCIMGroup",
    "SCIMGroupMetaType0",
    "SCIMListResponse",
    "SCIMMember",
    "SCIMPatchOp",
    "SCIMPatchOperation",
    "SCIMServiceProviderConfig",
    "SCIMServiceProviderConfigAuthenticationSchemesType0Item",
    "SCIMServiceProviderConfigMetaType0",
    "SCIMUser",
    "SCIMUserEmail",
    "SCIMUserGroup",
    "SCIMUserMetaType0",
    "SCIMUserName",
    "SearchTool",
    "SearchToolInfoResponse",
    "SearchToolInfoResponseLitellmParams",
    "SearchToolInfoResponseSearchToolInfoType0",
    "SearchToolLiteLLMParams",
    "SearchToolSearchToolInfoType0",
    "Skill",
    "SpendAnalyticsPaginatedResponse",
    "SpendCalculateRequest",
    "SpendCalculateRequestCompletionResponseType0",
    "SpendMetrics",
    "SSOConfig",
    "SSOSettingsResponse",
    "SSOSettingsResponseFieldSchema",
    "SSOSettingsResponseValues",
    "StreamingChoices",
    "TagActiveUsersResponse",
    "TagDeleteRequest",
    "TagInfoRequest",
    "TagNewRequest",
    "TagNewRequestModelInfoType0",
    "TagNewRequestModelMaxBudgetType0",
    "TagSummaryMetrics",
    "TagSummaryResponse",
    "TagUpdateRequest",
    "TagUpdateRequestModelInfoType0",
    "TagUpdateRequestModelMaxBudgetType0",
    "TeamAddMemberResponseMetadataType0",
    "TeamAddMemberResponseRouterSettingsType0",
    "TeamListResponse",
    "TeamMemberAddRequest",
    "TeamMemberAddResult",
    "TeamMemberAddResultUpdatedTeamMembershipType0",
    "TeamMemberAddResultUpdatedUserType0",
    "TeamMemberDeleteRequest",
    "TeamMemberUpdateRequest",
    "TeamMemberUpdateRequestRoleType0",
    "TeamMemberUpdateResponse",
    "TeamModelAddRequest",
    "TeamModelDeleteRequest",
    "TestPromptRequest",
    "TestPromptRequestConversationHistoryType0Item",
    "TestPromptRequestPromptVariablesType0",
    "TestSearchToolConnectionRequest",
    "TestSearchToolConnectionRequestLitellmParams",
    "TokenCountDetailsResponse",
    "TokenCountRequest",
    "TokenCountRequestContentsType0Item",
    "TokenCountRequestMessagesType0Item",
    "TokenCountResponse",
    "TokenCountResponseOriginalResponseType0",
    "ToolPermissionRule",
    "ToolPermissionRuleAllowedParamPatternsType0",
    "ToolPermissionRuleDecision",
    "TopLogprob",
    "TransformRequestBody",
    "TransformRequestBodyRequestBody",
    "UiDiscoveryEndpoints",
    "UISettings",
    "UISettingsResponse",
    "UISettingsResponseFieldSchema",
    "UISettingsResponseValues",
    "UIThemeConfig",
    "UIThemeSettingsResponse",
    "UIThemeSettingsResponseFieldSchema",
    "UIThemeSettingsResponseValues",
    "UiViewSpendLogsSpendLogsV2GetResponse200UiViewSpendLogsSpendLogsV2Get",
    "UpdateCostDiscountConfigConfigCostDiscountConfigPatchCostDiscountConfig",
    "UpdateCostMarginConfigConfigCostMarginConfigPatchCostMarginConfig",
    "UpdateCostMarginConfigConfigCostMarginConfigPatchCostMarginConfigAdditionalPropertyType1",
    "UpdateCustomerRequest",
    "UpdateCustomerRequestAllowedModelRegionType0",
    "UpdateDeployment",
    "UpdateGuardrailRequest",
    "UpdateLiteLLMParams",
    "UpdateLiteLLMParamsModelInfoType0",
    "UpdateLiteLLMParamsSearchContextCostPerQueryType0",
    "UpdateLiteLLMParamsTieredPricingType0Item",
    "UpdateLiteLLMParamsVertexCredentialsType1",
    "UpdateMCPServerRequest",
    "UpdateMCPServerRequestAuthTypeType0",
    "UpdateMCPServerRequestEnv",
    "UpdateMCPServerRequestMcpInfoType0",
    "UpdateMCPServerRequestStaticHeadersType0",
    "UpdateMCPServerRequestTransport",
    "UpdateModelGroupRequest",
    "UpdatePublicModelGroupsRequest",
    "UpdateSearchToolRequest",
    "UpdateTeamMemberPermissionsRequest",
    "UpdateTeamRequest",
    "UpdateTeamRequestMetadataType0",
    "UpdateTeamRequestModelAliasesType0",
    "UpdateTeamRequestModelRpmLimitType0",
    "UpdateTeamRequestModelTpmLimitType0",
    "UpdateTeamRequestRouterSettingsType0",
    "UpdateTeamRequestSecretManagerSettingsType0",
    "UpdateUsefulLinksRequest",
    "UpdateUsefulLinksRequestUsefulLinks",
    "UpdateUsefulLinksRequestUsefulLinksAdditionalPropertyType1",
    "UserAPIKeyAuth",
    "UserAPIKeyAuthAliases",
    "UserAPIKeyAuthAllowedModelRegionType0",
    "UserAPIKeyAuthConfig",
    "UserAPIKeyAuthLitellmBudgetTableType0",
    "UserAPIKeyAuthMetadata",
    "UserAPIKeyAuthModelMaxBudget",
    "UserAPIKeyAuthModelSpend",
    "UserAPIKeyAuthOrganizationMetadataType0",
    "UserAPIKeyAuthPermissions",
    "UserAPIKeyAuthRouterSettingsType0",
    "UserAPIKeyAuthRpmLimitPerModelType0",
    "UserAPIKeyAuthTeamMetadataType0",
    "UserAPIKeyAuthTeamModelAliasesType0",
    "UserAPIKeyAuthTpmLimitPerModelType0",
    "UserUpdateResult",
    "UserUpdateResultUpdatedUserType0",
    "ValidateBlockedWordsFileGuardrailsValidateBlockedWordsFilePostRequest",
    "ValidationError",
    "VectorStoreDeleteRequest",
    "VectorStoreInfoRequest",
    "VectorStoreUpdateRequest",
    "VectorStoreUpdateRequestVectorStoreMetadataType0",
)
